### ISSUE TITLE
你好,这个库用图片来搜索图片,例如人脸识别的效率如何

### ISSUE THREAD

**Issue by nine-city** [xmxoxo/vector_server#1]
你好,这个库用图片来搜索图片,例如人脸识别的效率如何

**Comment by xmxoxo** [comment]
可以用的。搜索的速度跟已有的图片数量有关，还跟生成的向量维度大小有关。具体用法可以参考博文中的例子，&nbsp;

只要得到了图片的特征向量，做索引就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "NineCity"<notifications@github.com&gt;; 
发送时间: 2020年11月19日(星期四) 下午4:13
收件人: "xmxoxo/vector_server"<vector_server@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [xmxoxo/vector_server] 你好,这个库用图片来搜索图片,例如人脸识别的效率如何 (#1)





 
你好,这个库用图片来搜索图片,例如人脸识别的效率如何

**Comment by nine-city** [comment]
但是目前我们的人脸数据是存在MYSQL里面的,这样也得一次性把所有的数据全部给拉出来放在内存里面去计算吗.

**Comment by xmxoxo** [comment]
使用向量搜索的话，加载图片的向量就可以了，就不需要数据库了。
